// <auto-generated />
namespace MyRentKit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class State : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(State));
        
        string IMigrationMetadata.Id
        {
            get { return "201712031525180_State"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
