// <auto-generated />
namespace MyRentKit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class datavalid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datavalid));
        
        string IMigrationMetadata.Id
        {
            get { return "201712132235248_datavalid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
